"""Validando Schema

Revision ID: af3e014e3871
Revises: 983c21d7554c
Create Date: 2026-03-26 11:52:16.279841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3e014e3871'
down_revision = '983c21d7554c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pendencia_token_acesso'), type_='unique')

    with op.batch_alter_table('segmento', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_segmento_nome'), ['nome'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_email'), type_='unique')

    with op.batch_alter_table('segmento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_segmento_nome'), type_='unique')

    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_pendencia_token_acesso'), ['token_acesso'])

    # ### end Alembic commands ###
